export const MESSAGE_TYPES = {
  CAPTURE_TAB: 'ELEMENT_SHOT_CAPTURE_TAB',
  CONTENT_PING: 'ELEMENT_SHOT_CONTENT_PING',
  OPEN_PREVIEW: 'ELEMENT_SHOT_OPEN_PREVIEW',
  PREVIEW_READY: 'ELEMENT_SHOT_PREVIEW_READY',
  SET_PREVIEW_DATA: 'ELEMENT_SHOT_SET_PREVIEW_DATA',
  START_PICK: 'ELEMENT_SHOT_START_PICK',
  START_PICK_REQUEST: 'ELEMENT_SHOT_START_PICK_REQUEST',
} as const;

export const CAPTURE_SETTLE_DELAY_MS = 120;

// Chrome currently permits at most two captureVisibleTab calls per second.
export const MIN_CAPTURE_INTERVAL_MS = 520;

export const DEFAULT_CAPTURE_INTERVAL_MS = MIN_CAPTURE_INTERVAL_MS;
export const MAX_CAPTURE_SEGMENTS = 200;

export const PICKER_SCRIPT_PATH = '/element-picker.js';
